package com.cmy.enums;


import org.apache.commons.lang3.StringUtils;

/**
 * @Author:Cmy
 * @Date:2023-11-23 15:37
 */
public enum MimeEnum {

    Mime323("323", "text/h323"),
    MimeAsx(".asx", "video/x-ms-asf"),
    MimeAcx(".acx", "application/internet-property-stream"),
    MimeAi(".ai", "application/postscript"),
    MimeAif(".aif", "audio/x-aiff"),
    MimeAiff(".aiff", "audio/aiff"),
    MimeAxs(".axs", "application/olescript"),
    MimeAifc(".aifc", "audio/aiff"),
    MimeAsr(".asr", "video/x-ms-asf"),
    MimeAvi(".avi", "video/x-msvideo"),
    MimeAsf(".asf", "video/x-ms-asf"),
    MimeAu(".au", "audio/basic"),
    MimeApplication(".application", "application/x-ms-application"),
    MimeBin(".bin", "application/octet-stream"),
    MimeBas(".bas", "text/plain"),
    MimeBcpio(".bcpio", "application/x-bcpio"),
    MimeBmp(".bmp", "image/bmp"),
    MimeCdf(".cdf", "application/x-cdf"),
    MimeCat(".cat", "application/vndms-pkiseccat"),
    MimeCrt(".crt", "application/x-x509-ca-cert"),
    MimeC(".c", "text/plain"),
    MimeCss(".css", "text/css"),
    MimeCer(".cer", "application/x-x509-ca-cert"),
    MimeCrl(".crl", "application/pkix-crl"),
    MimeCmx(".cmx", "image/x-cmx"),
    MimeCsh(".csh", "application/x-csh"),
    MimeCod(".cod", "image/cis-cod"),
    MimeCpio(".cpio", "application/x-cpio"),
    MimeClp(".clp", "application/x-msclip"),
    MimeCrd(".crd", "application/x-mscardfile"),
    MimeDeploy(".deploy", "application/octet-stream"),
    MimeDll(".dll", "application/x-msdownload"),
    MimeDot(".dot", "application/msword"),
    MimeDoc(".doc", "application/msword"),
    MimeDvi(".dvi", "application/x-dvi"),
    MimeDir(".dir", "application/x-director"),
    MimeDxr(".dxr", "application/x-director"),
    MimeDer(".der", "application/x-x509-ca-cert"),
    MimeDib(".dib", "image/bmp"),
    MimeDcr(".dcr", "application/x-director"),
    MimeDisco(".disco", "text/xml"),
    MimeExe(".exe", "application/octet-stream"),
    MimeEtx(".etx", "text/x-setext"),
    MimeEvy(".evy", "application/envoy"),
    MimeEml(".eml", "message/rfc822"),
    MimeEps(".eps", "application/postscript"),
    MimeFlr(".flr", "x-world/x-vrml"),
    MimeFif(".fif", "application/fractals"),
    MimeGtar(".gtar", "application/x-gtar"),
    MimeGif(".gif", "image/gif"),
    MimeGz(".gz", "application/x-gzip"),
    MimeHta(".hta", "application/hta"),
    MimeHtc(".htc", "text/x-component"),
    MimeHtt(".htt", "text/webviewhtml"),
    MimeH(".h", "text/plain"),
    MimeHdf(".hdf", "application/x-hdf"),
    MimeHlp(".hlp", "application/winhlp"),
    MimeHtml(".html", "text/html"),
    MimeHtm(".htm", "text/html"),
    MimeHqx(".hqx", "application/mac-binhex40"),
    MimeIsp(".isp", "application/x-internet-signup"),
    MimeIii(".iii", "application/x-iphone"),
    MimeIef(".ief", "image/ief"),
    MimeIvf(".ivf", "video/x-ivf"),
    MimeIns(".ins", "application/x-internet-signup"),
    MimeIco(".ico", "image/x-icon"),
    MimeJpg(".jpg", "image/jpeg"),
    MimeJfif(".jfif", "image/pjpeg"),
    MimeJpe(".jpe", "image/jpeg"),
    MimeJpeg(".jpeg", "image/jpeg"),
    MimeJs(".js", "application/x-javascript"),
    MimeLsx(".lsx", "video/x-la-asf"),
    MimeLatex(".latex", "application/x-latex"),
    MimeLsf(".lsf", "video/x-la-asf"),
    MimeManifest(".manifest", "application/x-ms-manifest"),
    MimeMhtml(".mhtml", "message/rfc822"),
    MimeMny(".mny", "application/x-msmoney"),
    MimeMht(".mht", "message/rfc822"),
    MimeMid(".mid", "audio/mid"),
    MimeMpv2(".mpv2", "video/mpeg"),
    MimeMan(".man", "application/x-troff-man"),
    MimeMvb(".mvb", "application/x-msmediaview"),
    MimeMpeg(".mpeg", "video/mpeg"),
    MimeM3u(".m3u", "audio/x-mpegurl"),
    MimeMdb(".mdb", "application/x-msaccess"),
    MimeMpp(".mpp", "application/vnd.ms-project"),
    MimeM1v(".m1v", "video/mpeg"),
    MimeMpa(".mpa", "video/mpeg"),
    MimeMe(".me", "application/x-troff-me"),
    MimeM13(".m13", "application/x-msmediaview"),
    MimeMovie(".movie", "video/x-sgi-movie"),
    MimeM14(".m14", "application/x-msmediaview"),
    MimeMpe(".mpe", "video/mpeg"),
    MimeMp2(".mp2", "video/mpeg"),
    MimeMov(".mov", "video/quicktime"),
    MimeMp3(".mp3", "audio/mpeg"),
    MimeMpg(".mpg", "video/mpeg"),
    MimeMs(".ms", "application/x-troff-ms"),
    MimeNc(".nc", "application/x-netcdf"),
    MimeNws(".nws", "message/rfc822"),
    MimeOda(".oda", "application/oda"),
    MimeOds(".ods", "application/oleobject"),
    MimePmc(".pmc", "application/x-perfmon"),
    MimeP7r(".p7r", "application/x-pkcs7-certreqresp"),
    MimeP7b(".p7b", "application/x-pkcs7-certificates"),
    MimeP7s(".p7s", "application/pkcs7-signature"),
    MimePmw(".pmw", "application/x-perfmon"),
    MimePs(".ps", "application/postscript"),
    MimeP7c(".p7c", "application/pkcs7-mime"),
    MimePbm(".pbm", "image/x-portable-bitmap"),
    MimePpm(".ppm", "image/x-portable-pixmap"),
    MimePub(".pub", "application/x-mspublisher"),
    MimePnm(".pnm", "image/x-portable-anymap"),
    MimePng(".png", "image/png"),
    MimePml(".pml", "application/x-perfmon"),
    MimeP10(".p10", "application/pkcs10"),
    MimePfx(".pfx", "application/x-pkcs12"),
    MimeP12(".p12", "application/x-pkcs12"),
    MimePdf(".pdf", "application/pdf"),
    MimePps(".pps", "application/vnd.ms-powerpoint"),
    MimeP7m(".p7m", "application/pkcs7-mime"),
    MimePko(".pko", "application/vndms-pkipko"),
    MimePpt(".ppt", "application/vnd.ms-powerpoint"),
    MimePmr(".pmr", "application/x-perfmon"),
    MimePma(".pma", "application/x-perfmon"),
    MimePot(".pot", "application/vnd.ms-powerpoint"),
    MimePrf(".prf", "application/pics-rules"),
    MimePgm(".pgm", "image/x-portable-graymap"),
    MimeQt(".qt", "video/quicktime"),
    MimeRa(".ra", "audio/x-pn-realaudio"),
    MimeRgb(".rgb", "image/x-rgb"),
    MimeRam(".ram", "audio/x-pn-realaudio"),
    MimeRmi(".rmi", "audio/mid"),
    MimeRas(".ras", "image/x-cmu-raster"),
    MimeRoff(".roff", "application/x-troff"),
    MimeRtf(".rtf", "application/rtf"),
    MimeRtx(".rtx", "text/richtext"),
    MimeSv4crc(".sv4crc", "application/x-sv4crc"),
    MimeSpc(".spc", "application/x-pkcs7-certificates"),
    MimeSetreg(".setreg", "application/set-registration-initiation"),
    MimeSnd(".snd", "audio/basic"),
    MimeStl(".stl", "application/vndms-pkistl"),
    MimeSetpay(".setpay", "application/set-payment-initiation"),
    MimeStm(".stm", "text/html"),
    MimeShar(".shar", "application/x-shar"),
    MimeSh(".sh", "application/x-sh"),
    MimeSit(".sit", "application/x-stuffit"),
    MimeSpl(".spl", "application/futuresplash"),
    MimeSct(".sct", "text/scriptlet"),
    MimeScd(".scd", "application/x-msschedule"),
    MimeSst(".sst", "application/vndms-pkicertstore"),
    MimeSrc(".src", "application/x-wais-source"),
    MimeSv4cpio(".sv4cpio", "application/x-sv4cpio"),
    MimeTex(".tex", "application/x-tex"),
    MimeTgz(".tgz", "application/x-compressed"),
    MimeT(".t", "application/x-troff"),
    MimeTar(".tar", "application/x-tar"),
    MimeTr(".tr", "application/x-troff"),
    MimeTif(".tif", "image/tiff"),
    MimeTxt(".txt", "text/plain"),
    MimeTexinfo(".texinfo", "application/x-texinfo"),
    MimeTrm(".trm", "application/x-msterminal"),
    MimeTiff(".tiff", "image/tiff"),
    MimeTcl(".tcl", "application/x-tcl"),
    MimeTexi(".texi", "application/x-texinfo"),
    MimeTsv(".tsv", "text/tab-separated-values"),
    MimeUstar(".ustar", "application/x-ustar"),
    MimeUls(".uls", "text/iuls"),
    MimeVcf(".vcf", "text/x-vcard"),
    MimeWps(".wps", "application/vnd.ms-works"),
    MimeWav(".wav", "audio/wav"),
    MimeWrz(".wrz", "x-world/x-vrml"),
    MimeWri(".wri", "application/x-mswrite"),
    MimeWks(".wks", "application/vnd.ms-works"),
    MimeWmf(".wmf", "application/x-msmetafile"),
    MimeWcm(".wcm", "application/vnd.ms-works"),
    MimeWrl(".wrl", "x-world/x-vrml"),
    MimeWdb(".wdb", "application/vnd.ms-works"),
    MimeWsdl(".wsdl", "text/xml"),
    MimeXap(".xap", "application/x-silverlight-app"),
    MimeXml(".xml", "text/xml"),
    MimeXlm(".xlm", "application/vnd.ms-excel"),
    MimeXaf(".xaf", "x-world/x-vrml"),
    MimeXla(".xla", "application/vnd.ms-excel"),
    MimeXls(".xls", "application/vnd.ms-excel"),
    MimeXof(".xof", "x-world/x-vrml"),
    MimeXlt(".xlt", "application/vnd.ms-excel"),
    MimeXlc(".xlc", "application/vnd.ms-excel"),
    MimeXsl(".xsl", "text/xml"),
    MimeXbm(".xbm", "image/x-xbitmap"),
    MimeXlw(".xlw", "application/vnd.ms-excel"),
    MimeXpm(".xpm", "image/x-xpixmap"),
    MimeXwd(".xwd", "image/x-xwindowdump"),
    MimeXsd(".xsd", "text/xml"),
    MimeZ(".z", "application/x-compress"),
    MimeZip(".zip", "application/x-zip-compressed"),
    MimeOctetStream(".*", "application/octet-stream");

    private final String suffix;

    private final String mimetype;

    public String getSuffix() {
        return suffix;
    }

    public String getMimetype() {
        return mimetype;
    }

    public static String getMimeTypeBySuffix(String suffix){
        if (StringUtils.isNotBlank(suffix)){
            for (MimeEnum mimeEnum : values()) {
                if (suffix.equals(mimeEnum.suffix)){
                    return mimeEnum.mimetype;
                }
            }
        }
        return MimeOctetStream.mimetype;
    }

    MimeEnum(String suffix, String mimetype) {
        this.suffix = suffix;
        this.mimetype = mimetype;
    }
}

